export const PRODUCT_ADD_REQUEST = "PRODUCT_ADD_REQUEST";
export const PRODUCT_ADDED = "PRODUCT_ADDED";
export const PRODUCT_ADD_ERROR = "PRODUCT_ADD_ERROR";
export const PRODUCT_READ_REQUEST = "PRODUCT_READ_REQUEST";
export const PRODUCT_READ = "PRODUCT_READ";
export const PRODUCT_ERROR = "PRODUCT_ERROR";